REVOKE USAGE ON SCHEMA graphql FROM authenticated;
REVOKE USAGE ON SCHEMA graphql FROM anon;
REVOKE ALL ON ALL TABLES IN SCHEMA graphql FROM authenticated;
REVOKE ALL ON ALL TABLES IN SCHEMA graphql FROM anon;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA graphql FROM authenticated;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA graphql FROM anon;